inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - node_modules/**/*
  TargetRubyVersion: '2.7.2'
  NewCops: enable
