inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - node_modules/**/*
    - bin/**/*
  TargetRubyVersion: '2.7.2'
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
