inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - node_modules/**/*
    - bin/**/*
    - config/**/*
  TargetRubyVersion: '2.7.2'
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

RSpec/ContextWording:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/ExampleLength:
  Max: 10
