default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: idea_app_development
  pool: 5
  username: root
  password: mysql
  host: localhost

development:
  <<: *default

test:
  <<: *default
  database: idea_app_test

production:
  <<: *default
  database: idea_app_production
